# Generated by Django 5.0.6 on 2024-07-17 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourspot', '0001_initial'),
        ('usersapp', '0005_alter_users_password_otpauthentication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('number_of_people', models.IntegerField()),
                ('message', models.TextField()),
                ('tourspot', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='tourspot.tourspot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersapp.users')),
            ],
        ),
    ]
