# Generated by Django 5.0.6 on 2024-07-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourspot', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourspot',
            name='entry_fee',
            field=models.IntegerField(max_length=50),
        ),
    ]
