# Generated by Django 5.0.6 on 2024-07-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourspot', '0005_alter_tourspot_entry_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='subtotal',
            field=models.IntegerField(default=120),
            preserve_default=False,
        ),
    ]
