# Generated by Django 5.0.6 on 2024-08-07 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourspot', '0007_alter_booking_message'),
        ('usersapp', '0007_favorite_unique_user_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.TextField(default='pending'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tourspot',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tourspot.tourspot'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usersapp.users'),
        ),
    ]
