# Generated by Django 5.0.6 on 2024-08-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourspot', '0008_booking_status_alter_booking_tourspot_and_more'),
        ('usersapp', '0007_favorite_unique_user_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='message',
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('user', 'tourspot', 'date'), name='unique_tourspot_booking'),
        ),
    ]
