# Generated by Django 5.0.6 on 2024-08-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourspot', '0009_alter_booking_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
