# Generated by Django 5.0.6 on 2024-08-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourspot', '0010_alter_booking_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='message',
            field=models.TextField(),
        ),
    ]
