# Generated by Django 5.0.6 on 2024-09-09 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourspot', '0011_alter_booking_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourspot',
            name='address',
        ),
        migrations.RemoveField(
            model_name='tourspot',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='tourspot',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tourspot',
            name='manager_name',
        ),
        migrations.RemoveField(
            model_name='tourspot',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tourspot',
            name='password',
        ),
        migrations.AddField(
            model_name='tourspot',
            name='tourspot_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tourspot',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
