# Generated by Django 5.0.6 on 2024-09-14 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourspot', '0012_remove_tourspot_address_remove_tourspot_contact_and_more'),
        ('usersapp', '0009_delete_otpauthentication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tourSpot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dayTour_reviews', to='tourspot.tourspot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dayTour_user', to='usersapp.users')),
            ],
        ),
    ]
