# Generated by Django 5.0.6 on 2024-09-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourspot', '0013_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourspot',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images/restaurant/menu/'),
        ),
    ]
