# Generated by Django 5.0.6 on 2024-07-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cuisine', models.CharField(max_length=200)),
                ('food_type', models.CharField(max_length=200)),
                ('ingredients', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('category', models.CharField(max_length=80)),
                ('size', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
    ]
