# Generated by Django 5.0.6 on 2024-07-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_menuitem_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70)),
                ('password', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=20)),
                ('cuisine', models.CharField(max_length=70)),
                ('food_type', models.CharField(max_length=70)),
                ('opening_time', models.CharField(max_length=70)),
                ('closing_time', models.CharField(max_length=70)),
                ('description', models.TextField()),
            ],
        ),
    ]
