# Generated by Django 5.0.6 on 2024-07-10 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_menu_restaurant_name_alter_menuitem_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant', null=True, blank=True),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
