# Generated by Django 5.0.6 on 2024-07-16 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='restaurant_name',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='restaurant.restaurant'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_item', to='restaurant.menu'),
        ),
    ]
