# Generated by Django 5.0.6 on 2024-07-16 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_alter_menu_restaurant_name_alter_menuitem_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_item', to='restaurant.restaurant'),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
