# Generated by Django 5.0.6 on 2024-07-16 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_review_delete_reviewandrating'),
        ('restaurant', '0011_remove_menuitem_menu_menuitem_restaurant_delete_menu'),
    ]

    operations = [
    ]
