# Generated by Django 5.0.6 on 2024-07-17 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_review_restaurant_delete_reviewandrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewAndRating',
        ),
    ]
