# Generated by Django 5.0.6 on 2024-07-17 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_delete_reviewandrating'),
        ('usersapp', '0005_alter_users_password_otpauthentication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='usersapp.users'),
        ),
    ]
