# Generated by Django 5.0.6 on 2024-08-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_alter_reservation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.TextField(default='pending'),
        ),
    ]
