# Generated by Django 5.0.6 on 2024-08-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_reservation_status'),
        ('usersapp', '0007_favorite_unique_user_restaurant'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('user', 'restaurant', 'start_time'), name='unique_restaurant_reservation'),
        ),
    ]
