# Generated by Django 5.0.6 on 2024-08-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_reservation_unique_restaurant_reservation'),
        ('usersapp', '0007_favorite_unique_user_restaurant'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservation',
            name='unique_restaurant_reservation',
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('user', 'restaurant', 'date', 'start_time'), name='unique_restaurant_reservation'),
        ),
    ]
