# Generated by Django 5.0.6 on 2024-09-09 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_restaurant_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='password',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='phone',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
