# Generated by Django 5.0.6 on 2024-09-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_remove_restaurant_address_remove_restaurant_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images/restaurant/'),
        ),
    ]
