# Generated by Django 5.0.6 on 2024-09-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0021_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images/restaurant/menu/'),
        ),
    ]
