# Generated by Django 5.0.6 on 2024-09-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0022_alter_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='images/restaurant/'),
        ),
    ]
