# Generated by Django 5.0.6 on 2024-07-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=50)),
                ('married', models.CharField(max_length=50)),
                ('passord', models.CharField(max_length=50)),
            ],
        ),
    ]
