# Generated by Django 5.0.6 on 2024-07-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_rename_passord_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='dob',
            field=models.CharField(max_length=200),
        ),
    ]
