# Generated by Django 5.0.6 on 2024-07-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0004_alter_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=500),
        ),
    ]
