# Generated by Django 5.0.6 on 2024-07-11 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0005_alter_users_password'),
        ('usersapp', '0005_alter_users_password_otpauthentication'),
    ]

    operations = [
    ]
