# Generated by Django 5.0.6 on 2024-07-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_alter_reservation_user'),
        ('usersapp', '0006_favorite'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'restaurant'), name='unique_user_restaurant'),
        ),
    ]
