# Generated by Django 5.0.6 on 2024-09-08 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0008_remove_users_address_remove_users_contact_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPAuthentication',
        ),
    ]
