# Generated by Django 5.0.6 on 2024-07-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
